### ISSUE TITLE
Binding not recognised in openHAB

### ISSUE THREAD

**Issue by LiaanLewis** [delid4ve/openhab-sonoff#1]
I hope you could assist
I implemented openhab3.0.1 on ubuntu.
I saved the jar in the bindings diretory and gave the file rwx rights

openhab is not picking up the binding.
Is there aversion issue or an operator error?

**Comment by delid4ve** [comment]
When you say it doesn't pick it up..
It won't show under bindings but will when you go to add a thing.
And you got the right branch yes?

**Comment by LiaanLewis** [comment]
Good day.
Thank you for your prompt reply.
It is firstly not visible under Bindings
If I try to add a new bindings I receive a list of 261 but Sonoff is not listed
If I add a new thing it asks me to select the binding. It is not showing in that list.
If I then want to add it I am back at the 261 list. 

It is as if it is not recognising the jar file in the /usr/share/openhabs/addons folder.
I see the other file in this directory has a .kar extension. Can this be the issue

ls /usr/share/openhab/addons

openhab-addons-3.0.1.kar  
org.openhab.binding.sonoff-2.5.11-SNAPSHOT.jar  
README

**Comment by delid4ve** [comment]
Your using the wrong jar (2.5.x) on openhab 3, where it says 'master' top left select the 3.x branch and there is a 3.0.1-snapshot jar there.

**Comment by LiaanLewis** [comment]
Thank you for your assistance!
It is working now.
